Switch over to a stack-based travis config

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,45 +1,87 @@
-# RRN: Copied from template here: https://github.com/hvr/multi-ghc-travis/blob/master/README.md#ghc-head-snapshots
-
 # NB: don't set `language: haskell` here
 
-# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
-env:
- # - CABALVER=1.18 GHCVER=7.8.2
- # - CABALVER=1.18 GHCVER=7.8.3
- # - CABALVER=1.18 GHCVER=7.8.4
-# Using new cabal only:
- - CABALVER=1.22 GHCVER=7.8.2
- - CABALVER=1.22 GHCVER=7.8.3
- - CABALVER=1.22 GHCVER=7.8.4
- - CABALVER=1.22 GHCVER=7.10.1
- - CABALVER=head GHCVER=head
+sudo: false
+cache:
+  directories:
+  - $HOME/.stack/
 
+# Here we test both stackage builds, which offer a controlled package
+# set, and "bleeding edge" builds which use the GHC resolver to grab
+# the latest off hackage.
 matrix:
+  include:
+    # Default: Use an LTS w/7.10, as embedded in stack.yaml currently:
+    - env: STACK_RESOLVER=
+
+    # Test with an older GHC, 7.8.4:
+    - env: STACK_RESOLVER=lts-2.22
+
+    # Test with GHC 8.0, not yet in LTS:
+    - env: STACK_RESOLVER=nightly-2016-05-31
+
+    # This is nondeterministic; the latest nightly:
+    - env: STACK_RESOLVER=nightly
+
+    # Try to use the very latest packages here, so that we catch
+    # failures before they get to stackage:
+    - env: STACK_RESOLVER=ghc-7.8
+    - env: STACK_RESOLVER=ghc-7.10
+    - env: STACK_RESOLVER=ghc-8.0
+      
   allow_failures:
-    - env: CABALVER=head GHCVER=head
+    # We should track these failures, but they don't represent a
+    # change or regression in our code:
+    - env: STACK_RESOLVER=ghc-7.8
+    - env: STACK_RESOLVER=ghc-7.10
+    - env: STACK_RESOLVER=ghc-8.0
+    - env: STACK_RESOLVER=nightly
 
-# Handle git submodules yourself
-git:
-    submodules: false
-
+    # Not worrying about this yet, but we will:
+    - env: STACK_RESOLVER=nightly-2016-05-31
+      
+addons:
+  apt:
+    packages:
+      - libgmp-dev
+      
 # Note: the distinction between `before_install` and `install` is not important.
+# This just sets up stack:
 before_install:
-# No Submodules atm [2015.04.26], disabling for now:
- # Use sed to replace the SSH URL with the public URL, then initialize submodules
-# - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
-# - git submodule update --init
+ - mkdir -p ~/.local/bin
+ - export PATH=~/.local/bin:$PATH
+ - if [ "$STACK_RESOLVER" == "" ];
+   then STACK="stack --no-terminal";
+   else STACK="stack --no-terminal --resolver=$STACK_RESOLVER";
+   fi
+ - export STACKVER=1.1.2
+ - wget https://github.com/commercialhaskell/stack/releases/download/v${STACKVER}/stack-${STACKVER}-linux-x86_64.tar.gz
+ - tar xvf stack-${STACKVER}-linux-x86_64.tar.gz
+ - mv -f stack-${STACKVER}-linux-x86_64/stack ~/.local/bin/
+ - chmod a+x ~/.local/bin/stack
 
- - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
-
+ # This sets up GHC and builds our packages:
 install:
- - cabal --version
- - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - travis_retry cabal update
- 
-# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
-script:
- - CABAL=cabal NOSETUP=1 ./.jenkins_script_cabal.sh
+ - stack setup
+ # This will fail with the ghc-7.X resolvers... We use the *main*
+ # stack.yaml to make this step reliable:
+ - stack --no-terminal --install-ghc install cabal-install
 
+ - $STACK setup 
+ # This should be deterministic for LTS releases, and others are
+ # expected to be nondeterministic anyway:
+ - if [ "$STACK_RESOLVER" != "" ];
+   then $STACK solver --update-config ;
+   fi
+ - $STACK exec ghc -- --version                    || echo '?'
+ - $STACK exec ghc ----print-project-git-commit-id || echo '?'
+ - $STACK build --test --no-run-tests
+
+ 
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+ - $STACK test 
+ - $STACK bench
+
+# notifications:
+#   email: false
